In [3]:
import pandas as pd

In [4]:
telecom_df = pd.read_csv(r"D:\CoWork\data\telecom_churn_processed.csv")

In [5]:
telecom_df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,0,False
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,False
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,True
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,True
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,False

In [6]:
telecom_df = telecom_df.drop(['customer_id',"pincode"], axis=1)
telecom_df["date_of_registration"] = pd.to_datetime(telecom_df["date_of_registration"])

In [7]:
telecom_df.columns

Index(['telecom_partner', 'gender', 'age', 'state', 'city',
       'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='str')

In [8]:
telecom_df["churn"] = telecom_df["churn"].map({True:1,False:0})
telecom_df["gender"] = telecom_df["gender"].map({"M":1,"F":0})

In [9]:
telecom_df["telecom_partner"].value_counts()

telecom_partner
Reliance Jio    61123
Airtel          60905
Vodafone        60802
BSNL            60723
Name: count, dtype: int64

In [10]:
telecom_encoded_df = pd.get_dummies(telecom_df, columns=["telecom_partner"], dtype = int)
telecom_encoded_df['date_of_registration'] = (telecom_df["date_of_registration"].max() - telecom_df["date_of_registration"]).dt.days

In [11]:
telecom_encoded_df.head()

,gender,age,state,city,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn,telecom_partner_Airtel,telecom_partner_BSNL,telecom_partner_Reliance Jio,telecom_partner_Vodafone
0,0,25,Karnataka,Kolkata,1219,4,124962,44,45,0,0,0,0,1,0
1,0,55,Mizoram,Mumbai,1219,2,130556,62,39,5973,0,0,0,1,0
2,0,57,Arunachal Pradesh,Delhi,1219,0,148828,49,24,193,1,0,0,0,1
3,1,46,Tamil Nadu,Kolkata,1219,1,38722,80,25,9377,1,0,1,0,0
4,0,26,Tripura,Delhi,1219,2,55098,78,15,1393,0,0,1,0,0

In [12]:
telecom_df.head()

,telecom_partner,gender,age,state,city,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,Reliance Jio,0,25,Karnataka,Kolkata,2020-01-01,4,124962,44,45,0,0
1,Reliance Jio,0,55,Mizoram,Mumbai,2020-01-01,2,130556,62,39,5973,0
2,Vodafone,0,57,Arunachal Pradesh,Delhi,2020-01-01,0,148828,49,24,193,1
3,BSNL,1,46,Tamil Nadu,Kolkata,2020-01-01,1,38722,80,25,9377,1
4,BSNL,0,26,Tripura,Delhi,2020-01-01,2,55098,78,15,1393,0

In [13]:
telecom_df.dtypes

telecom_partner                    str
gender                           int64
age                              int64
state                              str
city                               str
date_of_registration    datetime64[us]
num_dependents                   int64
estimated_salary                 int64
calls_made                       int64
sms_sent                         int64
data_used                        int64
churn                            int64
dtype: object

In [14]:
telecom_df.nunique()

telecom_partner              4
gender                       2
age                         57
state                       28
city                         6
date_of_registration      1220
num_dependents               5
estimated_salary        110032
calls_made                 109
sms_sent                    54
data_used                10917
churn                        2
dtype: int64

In [15]:
telecom_df.describe()

,gender,age,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
count,243553.000000,243553.000000,243553,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000
mean,0.599364,46.077609,2021-09-01 00:00:00.354748,1.997500,85021.137839,49.120122,24.015754,5001.354802,0.200478
min,0.000000,18.000000,2020-01-01 00:00:00,0.000000,20000.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,32.000000,2020-10-31 00:00:00,1.000000,52585.000000,24.000000,11.000000,2490.000000,0.000000
50%,1.000000,46.000000,2021-09-01 00:00:00,2.000000,84990.000000,49.000000,24.000000,4987.000000,0.000000
75%,1.000000,60.000000,2022-07-03 00:00:00,3.000000,117488.000000,74.000000,36.000000,7493.000000,0.000000
max,1.000000,74.000000,2023-05-04 00:00:00,4.000000,149999.000000,108.000000,53.000000,10991.000000,1.000000
std,0.490028,16.444029,NaN,1.414941,37508.963233,29.260198,14.611419,2927.420055,0.400359

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [17]:
telecom_encoded_df['estimated_salary_scaled'] = scaler.fit_transform(telecom_encoded_df[['estimated_salary']])

In [18]:
telecom_encoded_df.drop(columns= ["estimated_salary"], inplace=True)

In [19]:
telecom_encoded_df.head()

,gender,age,state,city,date_of_registration,num_dependents,calls_made,sms_sent,data_used,churn,telecom_partner_Airtel,telecom_partner_BSNL,telecom_partner_Reliance Jio,telecom_partner_Vodafone,estimated_salary_scaled
0,0,25,Karnataka,Kolkata,1219,4,44,45,0,0,0,0,1,0,1.064837
1,0,55,Mizoram,Mumbai,1219,2,62,39,5973,0,0,0,1,0,1.213975
2,0,57,Arunachal Pradesh,Delhi,1219,0,49,24,193,1,0,0,0,1,1.701113
3,1,46,Tamil Nadu,Kolkata,1219,1,80,25,9377,1,0,1,0,0,-1.234351
4,0,26,Tripura,Delhi,1219,2,78,15,1393,0,0,1,0,0,-0.797761

In [20]:
telecom_encoded_df.describe()

,gender,age,date_of_registration,num_dependents,calls_made,sms_sent,data_used,churn,telecom_partner_Airtel,telecom_partner_BSNL,telecom_partner_Reliance Jio,telecom_partner_Vodafone,estimated_salary_scaled
count,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,2.435530e+05
mean,0.599364,46.077609,609.999996,1.997500,49.120122,24.015754,5001.354802,0.200478,0.250069,0.249322,0.250964,0.249646,1.578900e-16
std,0.490028,16.444029,351.897027,1.414941,29.260198,14.611419,2927.420055,0.400359,0.433053,0.432621,0.433569,0.432809,1.000002e+00
min,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.733486e+00
25%,0.000000,32.000000,305.000000,1.000000,24.000000,11.000000,2490.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.647588e-01
50%,1.000000,46.000000,610.000000,2.000000,49.000000,24.000000,4987.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.301456e-04
75%,1.000000,60.000000,915.000000,3.000000,74.000000,36.000000,7493.000000,0.000000,1.000000,0.000000,1.000000,0.000000,8.655779e-01
max,1.000000,74.000000,1219.000000,4.000000,108.000000,53.000000,10991.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.732332e+00