In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

c:\Users\chandru.sivakumar\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\chandru.sivakumar\.cache\kagglehub\datasets\blastchar\telco-customer-churn\1.archive...

100%|██████████| 172k/172k [00:00<00:00, 217kB/s]

Extracting files...
Path to dataset files: C:\Users\chandru.sivakumar\.cache\kagglehub\datasets\blastchar\telco-customer-churn\versions\1

In [2]:
# import os

# os.listdir(path)

['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [3]:
# import shutil

# path_file = path + "\\WA_Fn-UseC_-Telco-Customer-Churn.csv"

# shutil.copy(path_file, "WA_Fn-UseC_-Telco-Customer-Churn.csv")

'WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [4]:
import pandas as pd

In [19]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [20]:
print(df.shape)
df.dtypes

(7043, 21)

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [21]:
null_summary = pd.DataFrame({
    'null_count': df.isnull().sum(),
    'null_percentage': (df.isnull().sum() / len(df)) * 100
})

print(null_summary)

                  null_count  null_percentage
customerID                 0              0.0
gender                     0              0.0
SeniorCitizen              0              0.0
Partner                    0              0.0
Dependents                 0              0.0
tenure                     0              0.0
PhoneService               0              0.0
MultipleLines              0              0.0
InternetService            0              0.0
OnlineSecurity             0              0.0
OnlineBackup               0              0.0
DeviceProtection           0              0.0
TechSupport                0              0.0
StreamingTV                0              0.0
StreamingMovies            0              0.0
Contract                   0              0.0
PaperlessBilling           0              0.0
PaymentMethod              0              0.0
MonthlyCharges             0              0.0
TotalCharges               0              0.0
Churn                      0              0.0

In [26]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [38]:
churn_count = pd.DataFrame({
    "Status": ["Churned", "Not Churned"],
    "Count": [
        df[df['Churn'] == "Yes"].shape[0],
        df[df['Churn'] == "No"].shape[0]
    ],
    "Percentage": [
        round(df[df['Churn'] == "Yes"].shape[0] / len(df) * 100, 2),
        round(df[df['Churn'] == "No"].shape[0] / len(df) * 100, 2)
    ]
})

churn_count

        Status  Count  Percentage
0      Churned   1869       26.54
1  Not Churned   5174       73.46

In [36]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"].isna().sum()

np.int64(11)

In [35]:
df["TotalCharges"].dtype

dtype('float64')

In [37]:
df[['tenure', 'MonthlyCharges', 'TotalCharges']].agg(['min', 'max', 'mean'])

         tenure  MonthlyCharges  TotalCharges
min    0.000000       18.250000     18.800000
max   72.000000      118.750000   8684.800000
mean  32.371149       64.761692   2283.300441